name: Upload
on:
  push:
    branches:
      - main
env:
  TZ: Asia/Shanghai
  HOST: i.wantmake.love
  USERNAME: root
  WEB_ROOT: /volume1/web/www/wechat-video-download
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "wechat-video-download.inject.js"
          target: "${{ env.WEB_ROOT }}"
